package intent_parser

var componentTypeChecks = []struct {
	keywords   []string
	typeName   string
	confidence float64
}{
	// React Hooks (highest priority)
	{
		keywords:   []string{"react hook", "react custom hook", "custom hook", "reactjs hook"},
		typeName:   "react-hook",
		confidence: 0.9,
	},
	// Vue Composables
	{
		keywords:   []string{"vue composable", "vuejs composable", "vue 3 composable"},
		typeName:   "vue-composable",
		confidence: 0.9,
	},
	// React Components (explicit)
	{
		keywords:   []string{"react component", "reactjs component", "react.js component", "react functional component"},
		typeName:   "react-component",
		confidence: 0.9,
	},
	// Vue Components (explicit)
	{
		keywords:   []string{"vue component", "vuejs component", "vue.js component", "vue 3 component"},
		typeName:   "vue-component",
		confidence: 0.9,
	},
	// React Framework
	{
		keywords:   []string{"react", "reactjs", "react.js", ".tsx", ".jsx"},
		typeName:   "react-component",
		confidence: 0.7,
	},
	// Vue Framework
	{
		keywords:   []string{"vue", "vuejs", "vue.js", ".vue"},
		typeName:   "vue-component",
		confidence: 0.7,
	},
	// Implicit (default to React)
	{
		keywords:   []string{"app", "application", "page", "widget", "component"},
		typeName:   "react-component",
		confidence: 0.5,
	},
}

var actionVerbs_90 = []string{
	// Primary creation verbs
	"create",
	"build",
	"make",
	"generate",
	"develop",
	"design",

	// Construction verbs
	"construct",
	"craft",
	"write",
	"code",
	"implement",

	// Request verbs
	"need",
	"want",
	"require",
	"looking for",
	"looking to",

	// Instruction verbs
	"show me",
	"give me",
	"provide",
	"help me create",
	"help me build",

	// Command verbs
	"add",
	"add a",
	"add an",
	"new",
	"new a",
	"new an",
}

var componentTypeWords_70 = []string{
	// React-specific
	"component",
	"react component",
	"reactjs component",
	"react.js component",
	"functional component",
	"class component",
	"fc", // React.FC shorthand

	// Vue-specific
	"vue component",
	"vuejs component",
	"vue.js component",

	// Hooks & Composables
	"hook",
	"react hook",
	"custom hook",
	"react custom hook",
	"composable",
	"vue composable",
	"composable function",

	// App/Application
	"app",
	"application",
	"web app",
	"web application",

	// Page/View
	"page",
	"view",
	"screen",
	"route",

	// UI Elements
	"widget",
	"module",
	"feature",
	"section",

	// Generic
	"element",
	"ui element",
	"frontend component",
}

var featureKeywords = map[string]string{
	// TypeScript
	"typescript":      "typescript",
	"ts":              "typescript",
	"type":            "typescript",
	"typed":           "typescript",
	"types":           "typescript",
	"interface":       "typescript",
	"type definition": "typescript",

	// Styling Libraries
	"tailwind":          "tailwind",
	"tailwindcss":       "tailwind",
	"tailwind css":      "tailwind",
	"tw":                "tailwind",
	"styled-components": "styled-components",
	"styled components": "styled-components",
	"styledcomponent":   "styled-components",
	"emotion":           "emotion",
	"css modules":       "css-modules",
	"cssmodules":        "css-modules",
	"css module":        "css-modules",
	"scss":              "scss",
	"sass":              "sass",
	"less":              "less",
	"css":               "css",
	"stylesheet":        "css",
	"styles":            "css",

	// State Management
	"useState":         "state",
	"use state":        "state",
	"state":            "state",
	"stateful":         "state",
	"state management": "state",
	"useReducer":       "reducer",
	"reducer":          "reducer",
	"redux":            "redux",
	"zustand":          "zustand",
	"jotai":            "jotai",
	"recoil":           "recoil",
	"mobx":             "mobx",
	"pinia":            "pinia",
	"vuex":             "vuex",

	// React Hooks
	"useEffect":    "hooks",
	"use effect":   "hooks",
	"useMemo":      "hooks",
	"use memo":     "hooks",
	"useCallback":  "hooks",
	"use callback": "hooks",
	"useRef":       "hooks",
	"use ref":      "hooks",
	"useContext":   "hooks",
	"use context":  "hooks",
	"custom hook":  "custom-hook",
	"custom hooks": "custom-hook",
	"hooks":        "hooks",
	"react hooks":  "hooks",

	// Vue Composables
	"composable":     "composable",
	"composables":    "composable",
	"vue composable": "composable",
	"use composable": "composable",

	// API & Data Fetching
	"api":         "api",
	"fetch":       "api",
	"axios":       "api",
	"http":        "api",
	"https":       "api",
	"rest":        "api",
	"restful":     "api",
	"graphql":     "graphql",
	"gql":         "graphql",
	"async":       "async",
	"await":       "async",
	"promise":     "async",
	"async await": "async",
	"async/await": "async",
	"loading":     "loading",
	"loader":      "loading",
	"spinner":     "loading",

	// Forms
	"form":            "form",
	"forms":           "form",
	"input":           "form",
	"textarea":        "form",
	"form select":     "form",
	"checkbox":        "form",
	"radio":           "form",
	"submit":          "form",
	"validation":      "validation",
	"validate":        "validation",
	"validator":       "validation",
	"formik":          "formik",
	"react hook form": "react-hook-form",
	"react-hook-form": "react-hook-form",
	"vee-validate":    "vee-validate",
	"vee validate":    "vee-validate",

	// Routing
	"router":           "routing",
	"routing":          "routing",
	"route":            "routing",
	"routes":           "routing",
	"navigation":       "routing",
	"navigate":         "routing",
	"react router":     "react-router",
	"react-router":     "react-router",
	"react router dom": "react-router",
	"vue router":       "vue-router",
	"vue-router":       "vue-router",

	// UI/UX Features
	"modal":           "modal",
	"dialog":          "modal",
	"popup":           "modal",
	"dropdown":        "dropdown",
	"tooltip":         "tooltip",
	"popover":         "popover",
	"accordion":       "accordion",
	"tabs":            "tabs",
	"carousel":        "carousel",
	"slider":          "slider",
	"pagination":      "pagination",
	"infinite scroll": "infinite-scroll",
	"infinite-scroll": "infinite-scroll",
	"lazy load":       "lazy-loading",
	"lazy loading":    "lazy-loading",
	"lazy-loading":    "lazy-loading",
	"virtual scroll":  "virtual-scroll",
	"virtual-scroll":  "virtual-scroll",

	// Animations
	"animation":     "animation",
	"animate":       "animation",
	"framer motion": "framer-motion",
	"framer-motion": "framer-motion",
	"framer":        "framer-motion",
	"react spring":  "react-spring",
	"react-spring":  "react-spring",
	"gsap":          "gsap",
	"transition":    "transition",
	"transitions":   "transition",

	// Testing
	"test":             "testing",
	"tests":            "testing",
	"testing":          "testing",
	"jest":             "jest",
	"vitest":           "vitest",
	"cypress":          "cypress",
	"playwright":       "playwright",
	"testing library":  "testing-library",
	"testing-library":  "testing-library",
	"unit test":        "testing",
	"unit tests":       "testing",
	"integration test": "testing",
	"e2e":              "e2e",
	"end to end":       "e2e",

	// Performance
	"memo":           "memo",
	"memoization":    "memo",
	"memoize":        "memo",
	"optimize":       "optimization",
	"optimization":   "optimization",
	"performance":    "optimization",
	"lazy":           "lazy-loading",
	"code split":     "code-splitting",
	"code-splitting": "code-splitting",
	"suspense":       "suspense",

	// Authentication
	"auth":           "auth",
	"authentication": "auth",
	"login":          "auth",
	"logout":         "auth",
	"signin":         "auth",
	"signout":        "auth",
	"signup":         "auth",
	"register":       "auth",
	"jwt":            "jwt",
	"token":          "auth",
	"session":        "auth",
	"oauth":          "oauth",
	"oauth2":         "oauth",

	// Internationalization
	"i18n":                 "i18n",
	"internationalization": "i18n",
	"localization":         "i18n",
	"locale":               "i18n",
	"translate":            "i18n",
	"translation":          "i18n",

	// Accessibility
	"a11y":          "accessibility",
	"accessibility": "accessibility",
	"aria":          "accessibility",
	"screen reader": "accessibility",
	"screenreader":  "accessibility",

	// Dark Mode
	"dark mode":  "dark-mode",
	"darkmode":   "dark-mode",
	"dark theme": "dark-mode",
	"darktheme":  "dark-mode",
	"theme":      "theme",
	"themes":     "theme",
	"light mode": "light-mode",
	"lightmode":  "light-mode",

	// Responsive
	"responsive":    "responsive",
	"mobile":        "responsive",
	"desktop":       "responsive",
	"tablet":        "responsive",
	"breakpoint":    "responsive",
	"breakpoints":   "responsive",
	"media query":   "responsive",
	"media queries": "responsive",

	// Error Handling
	"error":          "error-handling",
	"errors":         "error-handling",
	"error boundary": "error-boundary",
	"error-boundary": "error-boundary",
	"try catch":      "error-handling",
	"try-catch":      "error-handling",
	"exception":      "error-handling",

	// Props & Interfaces
	"props":      "props",
	"prop":       "props",
	"interfaces": "typescript",

	// Context
	"context":     "context",
	"context api": "context",
	"provide":     "context",
	"inject":      "context",

	// Events
	"event":         "events",
	"events":        "events",
	"onClick":       "events",
	"on click":      "events",
	"onChange":      "events",
	"on change":     "events",
	"handler":       "events",
	"handlers":      "events",
	"event handler": "events",
	"event-handler": "events",

	// Lifecycle
	"lifecycle":            "lifecycle",
	"mount":                "lifecycle",
	"unmount":              "lifecycle",
	"componentDidMount":    "lifecycle",
	"componentWillUnmount": "lifecycle",

	// Ref
	"ref":       "ref",
	"refs":      "ref",
	"createRef": "ref",
}

var commonPatterns_50 = map[string]string{
	"todo app":            "TodoApp",
	"login form":          "LoginForm",
	"user profile":        "UserProfile",
	"shopping cart":       "ShoppingCart",
	"nav bar":             "NavBar",
	"side bar":            "SideBar",
	"header":              "Header",
	"footer":              "Footer",
	"button":              "Button",
	"input":               "Input",
	"card":                "Card",
	"modal":               "Modal",
	"dialog":              "Dialog",
	"form":                "Form",
	"table":               "Table",
	"list":                "List",
	"menu":                "Menu",
	"dropdown":            "Dropdown",
	"tooltip":             "Tooltip",
	"popover":             "Popover",
	"alert":               "Alert",
	"badge":               "Badge",
	"avatar":              "Avatar",
	"spinner":             "Spinner",
	"loader":              "Loader",
	"progress":            "Progress",
	"slider":              "Slider",
	"switch":              "Switch",
	"checkbox":            "Checkbox",
	"radio":               "Radio",
	"select":              "Select",
	"textarea":            "Textarea",
	"search":              "Search",
	"filter":              "Filter",
	"pagination":          "Pagination",
	"breadcrumb":          "Breadcrumb",
	"tabs":                "Tabs",
	"accordion":           "Accordion",
	"carousel":            "Carousel",
	"gallery":             "Gallery",
	"grid":                "Grid",
	"layout":              "Layout",
	"container":           "Container",
	"wrapper":             "Wrapper",
	"section":             "Section",
	"article":             "Article",
	"aside":               "Aside",
	"nav":                 "Nav",
	"main":                "Main",
	"hero":                "Hero",
	"banner":              "Banner",
	"jumbotron":           "Jumbotron",
	"testimonial":         "Testimonial",
	"feature":             "Feature",
	"pricing":             "Pricing",
	"faq":                 "FAQ",
	"contact":             "Contact",
	"about":               "About",
	"home":                "Home",
	"dashboard":           "Dashboard",
	"settings":            "Settings",
	"profile":             "Profile",
	"account":             "Account",
	"auth":                "Auth",
	"login":               "Login",
	"signup":              "Signup",
	"signin":              "Signin",
	"signout":             "Signout",
	"register":            "Register",
	"forgot":              "Forgot",
	"reset":               "Reset",
	"verify":              "Verify",
	"confirm":             "Confirm",
	"activate":            "Activate",
	"deactivate":          "Deactivate",
	"delete":              "Delete",
	"edit":                "Edit",
	"update":              "Update",
	"create":              "Create",
	"save":                "Save",
	"cancel":              "Cancel",
	"submit":              "Submit",
	"back":                "Back",
	"next":                "Next",
	"prev":                "Prev",
	"previous":            "Previous",
	"close":               "Close",
	"open":                "Open",
	"toggle":              "Toggle",
	"expand":              "Expand",
	"collapse":            "Collapse",
	"show":                "Show",
	"hide":                "Hide",
	"view":                "View",
	"details":             "Details",
	"preview":             "Preview",
	"download":            "Download",
	"upload":              "Upload",
	"share":               "Share",
	"like":                "Like",
	"comment":             "Comment",
	"reply":               "Reply",
	"post":                "Post",
	"feed":                "Feed",
	"timeline":            "Timeline",
	"notification":        "Notification",
	"message":             "Message",
	"chat":                "Chat",
	"inbox":               "Inbox",
	"outbox":              "Outbox",
	"draft":               "Draft",
	"archive":             "Archive",
	"trash":               "Trash",
	"spam":                "Spam",
	"star":                "Star",
	"favorite":            "Favorite",
	"bookmark":            "Bookmark",
	"tag":                 "Tag",
	"category":            "Category",
	"sort":                "Sort",
	"query":               "Query",
	"result":              "Result",
	"item":                "Item",
	"product":             "Product",
	"cart":                "Cart",
	"checkout":            "Checkout",
	"order":               "Order",
	"payment":             "Payment",
	"invoice":             "Invoice",
	"receipt":             "Receipt",
	"refund":              "Refund",
	"return":              "Return",
	"exchange":            "Exchange",
	"warranty":            "Warranty",
	"support":             "Support",
	"ticket":              "Ticket",
	"issue":               "Issue",
	"bug":                 "Bug",
	"request":             "Request",
	"report":              "Report",
	"analytics":           "Analytics",
	"statistics":          "Statistics",
	"metrics":             "Metrics",
	"chart":               "Chart",
	"graph":               "Graph",
	"plot":                "Plot",
	"diagram":             "Diagram",
	"flowchart":           "Flowchart",
	"calendar":            "Calendar",
	"event":               "Event",
	"task":                "Task",
	"todo":                "Todo",
	"note":                "Note",
	"reminder":            "Reminder",
	"alarm":               "Alarm",
	"clock":               "Clock",
	"timer":               "Timer",
	"stopwatch":           "Stopwatch",
	"countdown":           "Countdown",
	"loading":             "Loading",
	"skeleton":            "Skeleton",
	"placeholder":         "Placeholder",
	"empty":               "Empty",
	"error":               "Error",
	"warning":             "Warning",
	"info":                "Info",
	"success":             "Success",
	"danger":              "Danger",
	"primary":             "Primary",
	"secondary":           "Secondary",
	"tertiary":            "Tertiary",
	"accent":              "Accent",
	"muted":               "Muted",
	"light":               "Light",
	"dark":                "Dark",
	"theme":               "Theme",
	"color":               "Color",
	"palette":             "Palette",
	"gradient":            "Gradient",
	"shadow":              "Shadow",
	"border":              "Border",
	"radius":              "Radius",
	"padding":             "Padding",
	"margin":              "Margin",
	"spacing":             "Spacing",
	"size":                "Size",
	"width":               "Width",
	"height":              "Height",
	"min":                 "Min",
	"max":                 "Max",
	"step":                "Step",
	"value":               "Value",
	"default":             "Default",
	"custom":              "Custom",
	"override":            "Override",
	"extend":              "Extend",
	"inherit":             "Inherit",
	"initial":             "Initial",
	"unset":               "Unset",
	"auto":                "Auto",
	"none":                "None",
	"hidden":              "Hidden",
	"visible":             "Visible",
	"opacity":             "Opacity",
	"transparent":         "Transparent",
	"solid":               "Solid",
	"dashed":              "Dashed",
	"dotted":              "Dotted",
	"double":              "Double",
	"groove":              "Groove",
	"ridge":               "Ridge",
	"inset":               "Inset",
	"outset":              "Outset",
	"normal":              "Normal",
	"bold":                "Bold",
	"bolder":              "Bolder",
	"lighter":             "Lighter",
	"100":                 "100",
	"200":                 "200",
	"300":                 "300",
	"400":                 "400",
	"500":                 "500",
	"600":                 "600",
	"700":                 "700",
	"800":                 "800",
	"900":                 "900",
	"italic":              "Italic",
	"oblique":             "Oblique",
	"underline":           "Underline",
	"overline":            "Overline",
	"line-through":        "LineThrough",
	"blink":               "Blink",
	"capitalize":          "Capitalize",
	"uppercase":           "Uppercase",
	"lowercase":           "Lowercase",
	"left":                "Left",
	"right":               "Right",
	"center":              "Center",
	"justify":             "Justify",
	"start":               "Start",
	"end":                 "End",
	"baseline":            "Baseline",
	"middle":              "Middle",
	"top":                 "Top",
	"bottom":              "Bottom",
	"stretch":             "Stretch",
	"space-between":       "SpaceBetween",
	"space-around":        "SpaceAround",
	"space-evenly":        "SpaceEvenly",
	"nowrap":              "Nowrap",
	"wrap":                "Wrap",
	"wrap-reverse":        "WrapReverse",
	"row":                 "Row",
	"column":              "Column",
	"row-reverse":         "RowReverse",
	"column-reverse":      "ColumnReverse",
	"flex":                "Flex",
	"inline-flex":         "InlineFlex",
	"block":               "Block",
	"inline":              "Inline",
	"inline-block":        "InlineBlock",
	"table-row":           "TableRow",
	"table-cell":          "TableCell",
	"table-header":        "TableHeader",
	"table-footer":        "TableFooter",
	"table-caption":       "TableCaption",
	"table-column":        "TableColumn",
	"table-column-group":  "TableColumnGroup",
	"table-row-group":     "TableRowGroup",
	"list-item":           "ListItem",
	"run-in":              "RunIn",
	"compact":             "Compact",
	"marker":              "Marker",
	"ruby":                "Ruby",
	"ruby-base":           "RubyBase",
	"ruby-text":           "RubyText",
	"ruby-base-container": "RubyBaseContainer",
	"ruby-text-container": "RubyTextContainer",
	"contents":            "Contents",
	"inline-grid":         "InlineGrid",
	"subgrid":             "Subgrid",
	"flow":                "Flow",
	"flow-root":           "FlowRoot",
	"inline-table":        "InlineTable",
}
